# Generated by Django 4.2.24 on 2025-09-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summarizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('topics', models.CharField(max_length=20)),
                ('sentiment', models.CharField(max_length=20)),
                ('keywords', models.CharField(max_length=20)),
            ],
        ),
    ]
