# Generated by Django 4.2.24 on 2025-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('topics', models.JSONField(default=list)),
                ('sentiment', models.CharField(max_length=10)),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Summarizer',
        ),
    ]
