# Generated by Django 4.2.24 on 2025-09-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0002_analysis_delete_summarizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
